services:
  - type: web
    name: insight-tools
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_KEY
        value: vape1098
